# Copyright (c) 2024 Maxwell Block
# This code is licensed under the MIT License.
# See the LICENSE file in the project root for license terms.

AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create resources for processing GuardDuty alerts with email notifications via SNS, and calls through Amazon Connect.

# The user will be prompted for these parameters before creating the stack
Parameters:
  SecurityPhoneNumber:
    Type: String
    Description: The phone number to call via Amazon Connect.
  ContactFlowId:
    Type: String
    Description: The Contact Flow ID for Amazon Connect.
  ConnectPhoneNumber:
    Type: String
    Description: The source phone number for Amazon Connect.
  EmailAddress:
    Type: String
    Description: The email address to receive SNS notifications.
  ConnectInstanceId:
    Type: String
    Description: The ID of the Amazon Connect instance.

Resources:
  # SNS Topic
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: GuardDuty Alerts

  # Subscription for an email to the SNS Topic
  MySNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref MySNSTopic
      Protocol: email
      Endpoint: !Ref EmailAddress

  # S3 bucket to store MP3 files used in call
  MyS3Bucket:
    Type: AWS::S3::Bucket

  MyS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowConnectInstanceAccess"
            Effect: "Allow"
            Principal:
              Service: "connect.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${S3BucketName}/*"
            Condition:
              StringEquals:
                "aws:SourceAccount": !Ref AWS::AccountId
              ArnLike:
                "aws:SourceArn": !Sub "arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}"

  # IAM role for the Lambda function to execute
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: LambdaLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: 
                  - "logs:CreateLogGroup"
                Resource: "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: 
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}:*"
        - PolicyName: LambdaSNSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "sns:Publish"
                Resource: "arn:aws:sns:*:*:*"
        - PolicyName: LambdaS3Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:ListBucket"
                Resource:
                  - "arn:aws:s3:::${S3BucketName}"
                  - "arn:aws:s3:::${S3BucketName}/*"
        - PolicyName: LambdaPollyConnectPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "polly:SynthesizeSpeech"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "connect:StartOutboundVoiceContact"
                  - "connect:StopContact"
                  - "connect:ListInstances"
                  - "connect:DescribeInstance"
                  - "connect:GetContactAttributes"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: 
                  - "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/connect/*"

  # Lambda function creation with the proper environment variables
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "GuardDutyAlertHandler"
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: "index.lambda_handler"
      Runtime: "python3.9"
      Code:
        ZipFile: |
          # Copyright (c) 2024 Maxwell Block
          # This code is licensed under the MIT License.
          # See the LICENSE file in the project root for license terms.

          import json
          import boto3
          import time
          import os

          def lambda_handler(event, context):
              # The event is a GuardDuty finding from EventBridge
              account_id = event.get('detail', {}).get('accountId', 'N/A')
              region = event.get('detail', {}).get('region', 'N/A')
              title = event.get('detail', {}).get('title', 'N/A')
              finding_type = event.get('detail', {}).get('type', 'N/A')
              time = event.get('detail', {}).get('updatedAt', 'N/A')
              
              # This is the message sent to emails
              message = (
                  "GuardDuty Alert\n\n"
                  "Account ID: " + account_id + "\n"
                  "Region: " + region + "\n"
                  "Title: " + title + "\n"
                  "Type: " + finding_type + "\n"
                  "Updated At: " + time + "\n"
              )
              
              sns_client = boto3.client('sns')

              sns_topic_arn = os.environ['SNS_TOPIC_ARN']
              
              response = sns_client.publish(
                  TopicArn=sns_topic_arn,
                  Message=message,
                  Subject='GuardDuty Alert'
              )
              
              print("Message sent to SNS:")

              # Converts the AWS account ID to be read off as a string 
              account_id_words = convert_number_to_words(account_id)
              
              # This is the spoken message read off in the call
              message_spoken = (
                  f"Hello, this is AWS notifying you of a critical GuardDuty alert impacting your AWS environment. "
                  f"In {account_id_words} within the {region} region, we have detected {title}. "
                  f"Please take action, thank you!"
              )
              
              polly_client = boto3.client('polly')
              
              response = polly_client.synthesize_speech(
                  Text=message_spoken,
                  OutputFormat='mp3',
                  VoiceId='Joanna'
              )
              
              mp3_file_path = '/tmp/output.mp3'
              with open('/tmp/output.mp3', 'wb') as file:
                  file.write(response['AudioStream'].read())
              
              # Upload the mp3 file to a S3 bucket
              s3_client = boto3.client('s3')
              bucket_name = os.environ['S3_BUCKET_NAME']
              s3_key = 'output.mp3'
              s3_client.upload_file(mp3_file_path, bucket_name, s3_key)

              time.sleep(30)  
              
              connect_client = boto3.client('connect')
              
              s3_url = f"https://s3.amazonaws.com/{bucket_name}/{s3_key}"

              # These are environment variables for Amazon Connect
              destination_phone_number = os.environ['DESTINATION_PHONE_NUMBER']
              contact_flow_id = os.environ['CONTACT_FLOW_ID']
              instance_id = os.environ['INSTANCE_ID']
              source_phone_number = os.environ['SOURCE_PHONE_NUMBER']
              
              # Initiate the outbound call
              response = connect_client.start_outbound_voice_contact(
                  DestinationPhoneNumber=destination_phone_number, 
                  ContactFlowId=contact_flow_id,  
                  InstanceId=instance_id, 
                  SourcePhoneNumber=source_phone_number,      
                  Attributes={
                      's3AudioUrl': s3_url
                  }
              )
              
              return {
                  'statusCode': 200,
                  'body': json.dumps('Called')
              }

          # Converts each number to a word
          def convert_number_to_words(number):
              number_map = {
                  '0': 'zero', '1': 'one', '2': 'two', '3': 'three', '4': 'four',
                  '5': 'five', '6': 'six', '7': 'seven', '8': 'eight', '9': 'nine'
              }
              return ' '.join(number_map[digit] for digit in str(number))

      Timeout: 120
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref MySNSTopic
          S3_BUCKET_NAME: !Ref S3BucketName
          DESTINATION_PHONE_NUMBER: !Ref SecurityPhoneNumber
          CONTACT_FLOW_ID: !Ref ContactFlowId
          INSTANCE_ID: !Ref ConnectInstanceId
          SOURCE_PHONE_NUMBER: !Ref ConnectPhoneNumber
          EMAIL_ADDRESS: !Ref EmailAddress

  # Allowing EventBridge permissions to invoke the Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt MyLambdaFunction.Arn
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt MyEventBridgeRule.Arn

  # EventBridge Rule for specific severity GuardDuty findings
  MyEventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - "aws.guardduty"
        detail-type:
          - "GuardDuty Finding"
        detail:
          severity:
            - 7
            - 8
            - 9
            - 10
      Targets:
        - Arn: !GetAtt MyLambdaFunction.Arn
          Id: "MyLambdaFunctionTarget"


Outputs:
  S3BucketName:
    Description: The name of the S3 bucket.
    Value: !Ref MyS3Bucket


